version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code

  db:
    image: postgres:12.4
    environment: 
      - POSTGRES_USER=futureproof
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
